name: Prune untagged Docker images
author: Fabien Schurter
description: >
  Fetches all the linked container packages of a given GitHub repository, and
  deletes their untagged versions.

runs:
  using: node16
  main: src/index.js

inputs:
  repository:
    description: The full name of the target GitHub repository.
    required: true

  gh_token:
    description: >
      A GitHub personal access token including at least the `read:packages` and
      `delete:packages` scopes.
    required: true
